#! /bin/sh

/home/leo/.scripts/autostart

num_monitors=$(xrandr --query | grep " connected" | wc -l)

if [ $num_monitors -lt 2 ]; then
    bspc monitor %eDP-1 -d I II III IV V VI VII VIII IX X
else
    bspc monitor "%eDP-1" -d I II III IV V
    bspc monitor "%HDMI-1-0" -d VI VII VIII IX X
    polybar external &
fi

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#757480"
bspc config normal_border_color "#211f27"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a conky state=floating border=off layer=below

bspc monitor
