#! /bin/sh

~/.scripts/autostart

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#757480"
bspc config normal_border_color "#211f27"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a conky state=floating border=off layer=below
