#! /bin/sh

# Applications to start on session start
# Intended to be called from bspwmrc or similar wm startup script

# Keybindings daemon
pkill -x sxhkd

# Window compositor
pkill -x picom

# Notification daemon
pkill -x dunst

# Network manager applet
pkill -x nm-applet

# Power manager
pkill -f xfce4-power-manager 

# External media manager
pkill -f parcellite 

# Power manager
pkill -x udiskie

# Session locker
pkill -x light-locker

# Volume icon
pkill -x volumeicon

# Microphone icon
pkill -x mictray

sleep 1

# launch polybar
$HOME/.config/polybar/launch.sh &

sxhkd &
picom &
dunst &
nm-applet &
parcellite &
udiskie -t &
volumeicon &
mictray &
xfce4-power-manager &
light-locker &

# Set wallpaper

WALLPAPER_AUX=$(awk '/file/' "${HOME}/.config/nitrogen/bg-saved.cfg" | head -n 1)
WALLPAPER=${WALLPAPER_AUX#*=}
WALLPAPER_ICON="${HOME}/.icons/Gladient/wallpaper.png"

if [ -f "${HOME}/.config/nitrogen/bg-saved.cfg" ]; then
    nitrogen --force-setter=xwindows --set-zoom-fill --save "${WALLPAPER}"
else
    dunstify 'Wallpaper' "<span size='larger'><u>Set a wallpaper!</u></span>" \
         -h string:synchronous:wallpaper-set \
         -a "Wallpaper" \
         -i "$WALLPAPER_ICON" \
         -u low
fi
