#! /bin/sh

# Applications to start on session start
# Intended to be called from bspwmrc or similar wm startup script

result=$(xrandr --query | grep "HDMI-1-0 connected")

sleep 1

# Check if the variable is not empty
if [ -n "$result" ]; then
    ~/.screenlayout/main.sh
    bspc monitor "%eDP-1" -d VI VII VIII IX X
    bspc monitor "%HDMI-1-0" -d I II III IV V
else
    ~/.screenlayout/laptop.sh
    bspc monitor "%eDP-1" -d I II III IV V VI VII VIII IX X
fi


# Keybindings daemon
pkill -x sxhkd

# Window compositor
pkill -x picom

# Notification daemon
pkill -x dunst

# Network manager applet
pkill -x nm-applet

# Power manager
pkill -f xfce4-power-manager 

# External media manager
pkill -f parcellite 

# Power manager
pkill -x udiskie

# Session locker
pkill -x light-locker

# Volume icon
pkill -x volumeicon

# Microphone icon
pkill -x mictray

# Redshift 
pkill -x redshift

sleep 1

# launch polybar
$HOME/.config/polybar/launch.sh &

sxhkd &
picom &
dunst &
nm-applet &
parcellite &
udiskie -t &
volumeicon &
mictray &
xfce4-power-manager &
light-locker &
redshift &
nitrogen --restore &
